ToDoAppProject/Article/urls.py
from django.urls import path
from .views import (
    ArticleDetailView,
    ArticleListView,
    ArticleCreateView,
    ArticleUpdateView,
    ArticleDeleteView,
    test_view
                    )

app_name = 'article'

urlpatterns = [
    path('', ArticleListView.as_view(), name='article-list'),
    path('create/', ArticleCreateView.as_view(), name='article-create'),
    path('test/', test_view, name='test'),
    path('<slug>/', ArticleDetailView.as_view(), name='article-detail'),
    path('<slug>/update/', ArticleUpdateView.as_view(), name='article-update'),
    path('<slug>/delete/', ArticleDeleteView.as_view(), name='article-delete'),
]

ToDoAppProject/ToDoAppProject/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/', include('post.urls')),
    path('article/', include('Article.urls')),
]

# if debug == TRUE (safeguard)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ToDoAppProject/post/urls.py
from django.urls import path
from .views import (
    PostDetailView,
    PostUpdateView,
    PostListView,
    PostCreateView,
    PostDeleteView,
                    )

app_name = 'post'

urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('create/', PostCreateView.as_view(), name='post-create'),
    path('<slug>/', PostDetailView.as_view(), name='post-detail'),
    path('<slug>/update/', PostUpdateView.as_view(), name='post-update'),
    path('<slug>/delete/', PostDeleteView.as_view(), name='post-delete'),

]

ToDoAppProject/Article/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.db.models.signals import pre_save
from ToDoAppProject.utils import unique_slug_generator



class Article(models.Model):
    title       = models.CharField(max_length=120)
    created     = models.DateTimeField(default=timezone.now)
    description = models.TextField(null=False)
    slug = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return f'{self.title}'

    def get_absolute_detail_url(self):
        return reverse("article:article-detail", kwargs={"slug": self.slug})


# pre save slug receiver
def slug_save(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance, instance.title, instance.slug)


pre_save.connect(slug_save, sender=Article)

ToDoAppProject/post/models.py
from django.db import models
from django.urls import reverse
from django.db.models.signals import pre_save, post_save
from ToDoAppProject.utils import unique_slug_generator



class Post(models.Model):
    title       = models.CharField(max_length=120)
    created     = models.DateTimeField(auto_now_add=True)
    description = models.TextField(null=False)
    slug = models.SlugField(max_length=50, unique=True)

    def __str__(self):
        return f'{self.title}'

    def get_absolute_detail_url(self):
        return reverse("post:post-detail", kwargs={"slug": self.slug})


# pre save slug receiver
def slug_save(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance, instance.title, instance.slug)


pre_save.connect(slug_save, sender=Post)

ToDoAppProject/Article/forms.py
from django import forms
from .models import Article


class ArticleModelForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Article's Name"}))

    class Meta:
        model = Article
        fields = [
            'title',
            'description'
        ]

ToDoAppProject/post/forms.py
from django import forms
from .models import Post

class PostModelForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Title'}))
    class Meta:
        model = Post
        fields = [
            'title',
            'description',
        ]

ToDoAppProject/Article/views.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    DeleteView,
)
from .mixins import AjaxFormMixin

from .forms import ArticleModelForm
from .models import Article


class ArticleListView(ListView):
    template_name = 'article/article_list.html'
    queryset = Article.objects.all()


class ArticleDetailView(DetailView):
    template_name = 'article/article_detail.html'

    def get_object(self, queryset=None):
        slug_= self.kwargs.get("slug")
        return get_object_or_404(Article, slug=slug_)


class ArticleCreateView(CreateView):
    template_name = 'article/article_create.html'
    form_class = ArticleModelForm
    queryset = Article.objects.all()
    success_url = reverse_lazy('article:article-list')

    def form_valid(self, form):
        return super().form_valid(form)


class ArticleUpdateView(AjaxFormMixin, UpdateView):
    template_name = 'article/article_update.html'
    form_class = ArticleModelForm
    queryset = Article.objects.all()
    success_url = reverse_lazy('article:article-list')

    def get_object(self, queryset=None):
        slug_ = self.kwargs.get("slug")
        return get_object_or_404(Article, slug=slug_)


class ArticleDeleteView(DeleteView):
    template_name = 'article/article_delete.html'

    def get_object(self):
        slug_= self.kwargs.get("slug")
        return get_object_or_404(Article, slug=slug_)

    def get_success_url(self):
        return reverse('article:article-list')


def test_view(request):
    template_name = 'article/article_test.html'
    context = {}
    return render(request, template_name, context)

ToDoAppProject/post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView,
    DeleteView,
)

from .forms import PostModelForm
from .models import Post


class PostListView(ListView):
    template_name = 'post/post_list.html'
    queryset = Post.objects.all()


class PostDetailView(DetailView):
    template_name = 'post/post_detail.html'

    def get_object(self, queryset=None):
        slug_= self.kwargs.get("slug")
        return get_object_or_404(Post, slug=slug_)


class PostCreateView(CreateView):
    template_name = 'post/post_create.html'
    form_class = PostModelForm
    queryset = Post.objects.all()
    success_url = reverse_lazy('post:post-list')

    def form_valid(self, form):
        return super().form_valid(form)


class PostUpdateView(UpdateView):
    template_name = 'post/post_update.html'
    form_class = PostModelForm
    queryset = Post.objects.all()
    success_url = reverse_lazy('post:post-list')

    def get_object(self, queryset=None):
        slug_ = self.kwargs.get("slug")
        return get_object_or_404(Post, slug=slug_)

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)


class PostDeleteView(DeleteView):
    template_name = 'post/post_delete.html'

    def get_object(self):
        slug_= self.kwargs.get("slug")
        return get_object_or_404(Post, slug=slug_)

    def get_success_url(self):
        return reverse('post:post-list')

ToDoAppProject/Article/templates/Article/article_create.html
{% extends "base.html" %}

{% block content %}
<div class="col-6 offset-m3">
 <form action='.' method='POST'> {% csrf_token %}
     {{ form.as_p }}
     <input type='submit' value='Save' />
 </form>
</div>
{% endblock content %}

ToDoAppProject/Article/templates/Article/article_delete.html
{% extends "base.html" %}

{% block content %}
<div class="col-6 offset-m3">
    <form method= 'POST'>{% csrf_token %}
        <h1>Do you want to delete the post "{{ object.title }}"?</h1>
        <p><input type='submit' value='Yes' />  <a href="{% url 'article:article-list' %}">Cancel</a></p>

    </form>
</div>
{% endblock content %}

ToDoAppProject/Article/templates/Article/article_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="col-6 offset-m3">
    <h3>{{ object.title }}</h3>
    <small>Created:{{ object.created }}</small>
    <p>{{ object.description|linebreaks }}</p>
    <a class="btn btn-primary" href = "{% url 'article:article-update' object.slug %}" role="button">Update</a>
</div>

{% endblock content %}

ToDoAppProject/Article/templates/Article/article_list.html
{% extends 'base.html' %}

{% block content %}
<div class="col-6 offset-m3">
    {% for instance in object_list %}
        <a href = '{{ instance.get_absolute_detail_url }}'> {{ instance.title }}</a>
        <br><small>Created on: {{ instance.created }}</small><br/>

            <!-- Button to Open the Modal -->
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
              Update
            </button>

            <!-- The Modal -->
            <div class="modal" id="myModal">
              <div class="modal-dialog">
                <div class="modal-content">

                  <!-- Modal Header -->
                  <div class="modal-header">
                    <h4 class="modal-title">Modal Heading</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                  </div>

                  <!-- Modal body -->
                  <div class="modal-body"> 
                      <div class="col-6 offset-m3">
                          <h1>Update: {{ instance.title }}</h1>
                          <form class="my-ajax-form" method="POST" data-url="{% url 'article:article-update' instance.slug  %}">  <!--data-url = sending this to new end point-->
                              {% csrf_token %}
                              <input type="text" class="my-ajax-form"  name ="title" placeholder="Title">
                              <input type="text" class="my-ajax-form" name = "description" placeholder="Description">
                              <input class='btn btn-primary' type='submit' value='Save' />
                          </form>
                      </div>
                  </div>

                  <!-- Modal footer -->
                  <div class="modal-footer">
                    <a class="btn btn-danger" href = "{% url 'article:article-list' %}" role="button">Close</a>
                  </div>

                </div>
              </div>
            </div>
        </p>
    {% endfor %}
</div>






{% endblock content %}

ToDoAppProject/Article/templates/Article/article_update.html
{% extends 'base.html' %}

{% block content %}
<div class="col-6 offset-m3">
    <h1>Update: {{ object.title }}</h1>
    <form class="my-ajax-form" method="POST" data-url="{% url 'article:article-update' object.slug %}">  <!--data-url = sending this to new end point-->
        {% csrf_token %}
        {{form.as_p}}
        <input class='btn btn-primary' type='submit' value='Save' />
    </form>
</div>
{% endblock content %}

<!-- 
{% block javascript %}
<script>
    $(document).ready(function(){
        var $myForm = $(".my-ajax-form")
        $myForm.submit(function(event){
            event.preventDefault()      //prevent form to submit a normal way (synchronus way)
            var $formData = $(this).serialize()
            var $endpoint = $myForm.attr("data-url") || window.location.href
            console.log($formData)
            console.log($endpoint)
            $.ajax({
                method:"POST",
                url: $endpoint,
                data: $formData,
                success: handleFormSuccess,
                error: handleFormError,
            })

            function handleFormSuccess(data, textStatus, jqXHR){
                console.log(data)
                console.log(textStatus)
                console.log(jqXHR)
                $myForm[0].reset();    //reset form data
            }

            function handleFormError(jqXHR, textStatus, errorThrown){
                console.log(jqXHR)
                console.log(textStatus)
                console.log(errorThrown)
            }
        })
    })
</script>
{% endblock javascript %} -->

ToDoAppProject/post/templates/post/post_create.html
{% extends "base.html" %}

{% block content %}
 <form action='.' method='POST'> {% csrf_token %}
     {{ form.as_p }}
     <input type='submit' value='Save' />
 </form>
{% endblock content %}

ToDoAppProject/post/templates/post/post_delete.html
{% extends "base.html" %}

{% block content %}

<form method= 'POST'>{% csrf_token %}
    <h1>Do you want to delete the post "{{ object.title }}"?</h1>
    <p><input type='submit' value='Yes' />  <a href="{% url 'post:post-list' %}">Cancel</a></p>

</form>

{% endblock content %}

ToDoAppProject/post/templates/post/post_detail.html
{% extends 'base.html' %}


{% block content %}

    <h1>{{ object.title }}</h1>
    <small>Created:{{ object.created }}</small>
    <p>{{ object.description|linebreaks }}</p>

{% endblock content %}

ToDoAppProject/post/templates/post/post_list.html
{% extends 'base.html' %}

{% block content %}

    {% for instance in object_list %}
        <a href = '{{ instance.get_absolute_detail_url }}'> {{ instance.title }}</a>
        <br><small>Created on: {{ post.created }}</small></br>

            <!-- Button to Open the Modal -->
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
              Update
            </button>

            <!-- The Modal -->
            <div class="modal" id="myModal">
              <div class="modal-dialog">
                <div class="modal-content">

                  <!-- Modal Header -->
                  <div class="modal-header">
                    <h4 class="modal-title">Modal Heading</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                  </div>

                  <!-- Modal body -->
                  <div class="modal-body">
                    Modal body..
                  </div>

                  <!-- Modal footer -->
                  <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                  </div>

                </div>
              </div>
            </div>
        </p>
    {% endfor %}

{% endblock content %}

ToDoAppProject/post/templates/post/post_update.html
{% extends 'base.html' %}

{% block content %}
    <h1>Update: {{object.name}}</h1>
    <form method='POST'>{% csrf_token %}
        {{form.as_p}}
        <input type='submit' value='Save' />
    </form>
{% endblock content %}

ToDoAppProject/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>To Do App Project</title>
    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static '/css/base.css' %}" />
</head>
<body>

    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1> To Do App </h1>
        </div>
    </div>

    {% include 'nav_bar.html' %}


    {% block content %}
    replace me
    {% endblock content %}


    <!--Bootstrap Jquery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <!--ajax call-->
    <script src="{% static '/js/ajax_call.js' %}"></script>

</body>
</html>

ToDoAppProject/templates/nav_bar.html
<!-- A grey horizontal navbar that becomes vertical on small screens -->
<nav class="navbar navbar-expand-sm bg-light">

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="../">Back</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'article:article-list' %}">Post List</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'article:article-create' %}">Create Post</a>
    </li>
  </ul>

</nav>